// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export namespace NetSchemas{
export enum Data{
  NONE= 0,
  ClientConnected= 1,
  ClientDisconnected= 2,
  Heartbeat= 3
};

export function unionToData(
  type: Data,
  accessor: (obj:NetSchemas.ClientConnected|NetSchemas.ClientDisconnected|NetSchemas.Heartbeat) => NetSchemas.ClientConnected|NetSchemas.ClientDisconnected|NetSchemas.Heartbeat|null
): NetSchemas.ClientConnected|NetSchemas.ClientDisconnected|NetSchemas.Heartbeat|null {
  switch(NetSchemas.Data[type]) {
    case 'NONE': return null; 
    case 'ClientConnected': return accessor(new NetSchemas.ClientConnected())! as NetSchemas.ClientConnected;
    case 'ClientDisconnected': return accessor(new NetSchemas.ClientDisconnected())! as NetSchemas.ClientDisconnected;
    case 'Heartbeat': return accessor(new NetSchemas.Heartbeat())! as NetSchemas.Heartbeat;
    default: return null;
  }
}

export function unionListToData(
  type: Data, 
  accessor: (index: number, obj:NetSchemas.ClientConnected|NetSchemas.ClientDisconnected|NetSchemas.Heartbeat) => NetSchemas.ClientConnected|NetSchemas.ClientDisconnected|NetSchemas.Heartbeat|null, 
  index: number
): NetSchemas.ClientConnected|NetSchemas.ClientDisconnected|NetSchemas.Heartbeat|null {
  switch(NetSchemas.Data[type]) {
    case 'NONE': return null; 
    case 'ClientConnected': return accessor(index, new NetSchemas.ClientConnected())! as NetSchemas.ClientConnected;
    case 'ClientDisconnected': return accessor(index, new NetSchemas.ClientDisconnected())! as NetSchemas.ClientDisconnected;
    case 'Heartbeat': return accessor(index, new NetSchemas.Heartbeat())! as NetSchemas.Heartbeat;
    default: return null;
  }
}
}

/**
 * @constructor
 */
export namespace NetSchemas{
export class ClientConnected {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ClientConnected
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ClientConnected {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientConnected= obj
 * @returns ClientConnected
 */
static getRootAsClientConnected(bb:flatbuffers.ByteBuffer, obj?:ClientConnected):ClientConnected {
  return (obj || new ClientConnected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientConnected= obj
 * @returns ClientConnected
 */
static getSizePrefixedRootAsClientConnected(bb:flatbuffers.ByteBuffer, obj?:ClientConnected):ClientConnected {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientConnected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Builder builder
 */
static startClientConnected(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endClientConnected(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createClientConnected(builder:flatbuffers.Builder):flatbuffers.Offset {
  ClientConnected.startClientConnected(builder);
  return ClientConnected.endClientConnected(builder);
}
}
}
/**
 * @constructor
 */
export namespace NetSchemas{
export class ClientDisconnected {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ClientDisconnected
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ClientDisconnected {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientDisconnected= obj
 * @returns ClientDisconnected
 */
static getRootAsClientDisconnected(bb:flatbuffers.ByteBuffer, obj?:ClientDisconnected):ClientDisconnected {
  return (obj || new ClientDisconnected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientDisconnected= obj
 * @returns ClientDisconnected
 */
static getSizePrefixedRootAsClientDisconnected(bb:flatbuffers.ByteBuffer, obj?:ClientDisconnected):ClientDisconnected {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientDisconnected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Builder builder
 */
static startClientDisconnected(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endClientDisconnected(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createClientDisconnected(builder:flatbuffers.Builder):flatbuffers.Offset {
  ClientDisconnected.startClientDisconnected(builder);
  return ClientDisconnected.endClientDisconnected(builder);
}
}
}
/**
 * @constructor
 */
export namespace NetSchemas{
export class Heartbeat {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Heartbeat
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Heartbeat {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Heartbeat= obj
 * @returns Heartbeat
 */
static getRootAsHeartbeat(bb:flatbuffers.ByteBuffer, obj?:Heartbeat):Heartbeat {
  return (obj || new Heartbeat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Heartbeat= obj
 * @returns Heartbeat
 */
static getSizePrefixedRootAsHeartbeat(bb:flatbuffers.ByteBuffer, obj?:Heartbeat):Heartbeat {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Heartbeat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Builder builder
 */
static startHeartbeat(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHeartbeat(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHeartbeat(builder:flatbuffers.Builder):flatbuffers.Offset {
  Heartbeat.startHeartbeat(builder);
  return Heartbeat.endHeartbeat(builder);
}
}
}
/**
 * @constructor
 */
export namespace NetSchemas{
export class Message {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Message
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getSizePrefixedRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
messageId():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns NetSchemas.Data
 */
dataType():NetSchemas.Data {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : NetSchemas.Data.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
data<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMessage(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param number messageId
 */
static addMessageId(builder:flatbuffers.Builder, messageId:number) {
  builder.addFieldInt16(0, messageId, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param NetSchemas.Data dataType
 */
static addDataType(builder:flatbuffers.Builder, dataType:NetSchemas.Data) {
  builder.addFieldInt8(1, dataType, NetSchemas.Data.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createMessage(builder:flatbuffers.Builder, messageId:number, dataType:NetSchemas.Data, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  Message.startMessage(builder);
  Message.addMessageId(builder, messageId);
  Message.addDataType(builder, dataType);
  Message.addData(builder, dataOffset);
  return Message.endMessage(builder);
}
}
}
